[versions]
accompanist="0.11.1"
activityCompose="1.3.0-beta01"
appCompat="1.4.0-alpha02"
coil="1.2.2"
compose="1.0.0-beta08"
daggerHilt="2.36"
datetime-dialogs="0.4.2"
desugar="1.1.5"
gradlePlugins-agp="7.0.0-beta03"
gradlePlugins-crashlytics="2.7.0"
gradlePlugins-gms="4.3.8"
hilt="1.0.0"
hiltLifecycleViewmodel="1.0.0-alpha03"
hiltNavigationCompose="1.0.0-alpha02"
kotlin="1.5.10"
lifecycle="2.4.0-alpha01"
lifecycleViewmodelCompose="1.0.0-alpha06"
navigationCompose="2.4.0-alpha02"
room="2.4.0-alpha02"
timber="4.7.1"

[libraries]
androidx-activity-activityCompose={ module="androidx.activity:activity-compose", version.ref="activityCompose" }
androidx-appCompat={ module="androidx.appcompat:appcompat", version.ref="appCompat" }
androidx-compose-compiler={ module="androidx.compose.compiler:compiler", version.ref="compose" }
androidx-compose-foundation={ module="androidx.compose.foundation:foundation", version.ref="compose" }
androidx-compose-material={ module="androidx.compose.material:material", version.ref="compose" }
androidx-compose-materialIconsExtended={ module="androidx.compose.material:material-icons-extended", version.ref="compose" }
androidx-compose-runtimeLivedata={ module="androidx.compose.runtime:runtime-livedata", version.ref="compose" }
androidx-compose-ui={ module="androidx.compose.ui:ui", version.ref="compose" }
androidx-compose-uiTooling={ module="androidx.compose.ui:ui-tooling", version.ref="compose" }
androidx-hilt-hiltCommon={ module="androidx.hilt:hilt-common", version.ref="hilt" }
androidx-hilt-hiltCompiler={ module="androidx.hilt:hilt-compiler", version.ref="hilt" }
androidx-hilt-hiltLifecycleViewmodel={ module="androidx.hilt:hilt-lifecycle-viewmodel", version.ref="hiltLifecycleViewmodel" }
androidx-hilt-hiltNavigationCompose={ module="androidx.hilt:hilt-navigation-compose", version.ref="hiltNavigationCompose" }
androidx-lifecycle-lifecycleRuntimeKtx={ module="androidx.lifecycle:lifecycle-runtime-ktx", version.ref="lifecycle" }
androidx-lifecycle-lifecycleViewmodelCompose={ module="androidx.lifecycle:lifecycle-viewmodel-compose", version.ref="lifecycleViewmodelCompose" }
androidx-navigation-navigationCompose={ module="androidx.navigation:navigation-compose", version.ref="navigationCompose" }
androidx-room-roomCompiler={ module="androidx.room:room-compiler", version.ref="room" }
androidx-room-roomKtx={ module="androidx.room:room-ktx", version.ref="room" }
androidx-room-roomRuntime={ module="androidx.room:room-runtime", version.ref="room" }
com-android-tools-desugar={ module="com.android.tools:desugar_jdk_libs", version.ref="desugar" }
coilKt-coil={ module="io.coil-kt:coil", version.ref="coil" }
google-accompanistCoil={ module="com.google.accompanist:accompanist-coil", version.ref="accompanist" }
google-accompanistFlowLayout={ module="com.google.accompanist:accompanist-flowlayout", version.ref="accompanist" }
google-accompanistPager={ module="com.google.accompanist:accompanist-pager", version.ref="accompanist" }
google-accompanistPagerIndicators={ module="com.google.accompanist:accompanist-pager-indicators", version.ref="accompanist" }
google-accompanistSystemUIController={ module="com.google.accompanist:accompanist-systemuicontroller", version.ref="accompanist" }
google-dagger-dagger={ module="com.google.dagger:dagger", version.ref="daggerHilt" }
google-dagger-daggerCompiler={ module="com.google.dagger:dagger-compiler", version.ref="daggerHilt" }
google-dagger-hiltAndroid={ module="com.google.dagger:hilt-android", version.ref="daggerHilt" }
google-dagger-hiltCompiler={ module="com.google.dagger:hilt-compiler", version.ref="daggerHilt" }
gradlePlugins-android={ module="com.android.tools.build:gradle", version.ref="gradlePlugins-agp" }
gradlePlugins-crashlytics={ module="com.google.firebase:firebase-crashlytics-gradle", version.ref="gradlePlugins-crashlytics" }
gradlePlugins-gms={ module="com.google.gms:google-services", version.ref="gradlePlugins-gms" }
gradlePlugins-hilt={ module="com.google.dagger:hilt-android-gradle-plugin", version.ref="daggerHilt" }
gradlePlugins-kotlin={ module="org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref="kotlin" }
io-github-vanpra-dialogs-datetime={ module="io.github.vanpra.compose-material-dialogs:datetime", version.ref="datetime-dialogs" }
jakes-timber-timber={ module="com.jakewharton.timber:timber", version.ref="timber" }

[bundles]
accompanist=["google-accompanistCoil", "google-accompanistFlowLayout", "google-accompanistPager", "google-accompanistPagerIndicators", "google-accompanistSystemUIController"]
compose=["androidx-compose-compiler", "androidx-compose-foundation", "androidx-compose-material", "androidx-compose-materialIconsExtended", "androidx-compose-runtimeLivedata", "androidx-compose-ui", "androidx-compose-uiTooling"]
hilt=["google-dagger-dagger", "google-dagger-hiltAndroid", "androidx-hilt-hiltCommon", "androidx-hilt-hiltLifecycleViewmodel"]
hiltKapt=["google-dagger-daggerCompiler", "google-dagger-hiltCompiler", "androidx-hilt-hiltCompiler"]
lifecycle=["androidx-lifecycle-lifecycleRuntimeKtx", "androidx-lifecycle-lifecycleViewmodelCompose"]
room=["androidx-room-roomKtx", "androidx-room-roomRuntime"]
