name: buildbot

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: android-actions/setup-android@v2
        name: Set up Android SDK

      - name: Check for dependency updates
        uses: gradle/gradle-command-action@v2
        with:
          arguments: app:staticAnalysis app:collectSarifReports --continue

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: app/build/reports/sarif/

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: android-actions/setup-android@v2
        name: Set up Android SDK

      - name: Run tests with Gradle
        uses: gradle/gradle-command-action@v2
        with:
          arguments: test --continue --no-daemon
